import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  fr: {
    // Navigation
    'nav.track': 'Suivi & Réservation',
    'nav.fleet': 'Notre Flotte',
    'nav.portal': 'Espace Voyageur',
    'nav.reportIssue': 'Réclamation',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    'nav.role': 'Changer de profil',
    'nav.notifications': 'Notifications',
    'nav.switchRole': 'Accès rapide démo',
    'nav.deboraAdmin': 'Admin Débora',
    'nav.adminPortal': 'Portail Admin',
    'nav.agentDouala': 'Agent Douala',
    'nav.agentYaounde': 'Agent Yaoundé',
    'nav.driver': 'Conducteur Bus',
    'nav.customer': 'Client (Alice)',

    // Auth Modal
    'auth.titleLogin': 'Connexion Espace Membre',
    'auth.titleRegister': 'Créer un Compte',
    'auth.identifier': 'Identifiant ou E-mail',
    'auth.identifierPlaceholder': 'ex: debora ou adresse@email.com',
    'auth.password': 'Mot de passe',
    'auth.passwordPlaceholder': '••••••••',
    'auth.fullName': 'Nom complet',
    'auth.fullNamePlaceholder': 'ex: Jean Dupont',
    'auth.phone': 'Numéro de Téléphone (Facultatif)',
    'auth.btnLogin': 'Se connecter en toute sécurité',
    'auth.btnRegister': 'Créer mon compte',
    'auth.submitting': 'Authentification en cours...',
    'auth.quickAccess': 'Accès rapide démo (1-clic)',
    'auth.deboraHint': 'Compte Admin configuré :',
    'auth.deboraBtn': 'Connexion 1-clic debora',

    // Hero & Search
    'hero.badge': 'Réseau National Interurbain',
    'hero.title': 'Voyagez et expédiez en toute sérénité',
    'hero.subtitle': 'Liaisons quotidiennes Douala ↔ Yaoundé et messagerie express sous géolocalisation GPS directe.',
    'tab.track': 'Suivre un Colis',
    'tab.book': 'Rechercher un Trajet',
    'tab.map': 'Carte & Endroits en Direct',
    'track.placeholder': 'Entrez votre N° de suivi (ex: GV-2026-9042)',
    'track.btn': 'Localiser le colis',
    'track.quickDemo': 'Exemples récents :',
    'track.searching': 'Recherche du colis...',
    'track.refresh': 'Actualiser',
    'track.copied': 'Copié !',
    'track.copy': 'Copier le code',
    'book.origin': 'Gare de Départ',
    'book.destination': 'Gare d\'Arrivée',
    'book.date': 'Date de voyage',
    'book.btn': 'Trouver les départs',
    'book.price': 'FCFA',
    'book.reserve': 'Réserver',
    'book.seats': 'places',
    'book.noTrips': 'Aucun départ programmé sur cette ligne pour le moment.',
    'book.availableTrips': 'Départs disponibles :',
    'book.directLink': 'Liaison directe',
    'book.history': 'Historique des étapes de transport',

    // Tracking Board
    'status.origin': 'Gare Départ',
    'status.transit': 'En Transit (Bus)',
    'status.destination': 'Gare Arrivée',
    'status.speed': 'Vitesse',
    'status.battery': 'Batterie balise',
    'status.sender': 'Expéditeur',
    'status.recipient': 'Destinataire',
    'status.weight': 'Poids',
    'status.lastPing': 'Mis à jour',
    'status.incidentReported': 'Incident / perturbation signalé :',
    'status.reportIssue': 'Signaler un problème sur ce colis',

    // Fleet Showcase
    'fleet.title': 'L\'Excellence du Transport Interurbain',
    'fleet.subtitle': 'Des autocars récents de standing international et des gares modernes conçues pour votre confort.',
    'fleet.vipTitle': 'Confort VIP Première Classe',
    'fleet.vipDesc': 'Fauteuils en cuir inclinables, climatisation régulée, prises de recharge et suspension pneumatique pour un repos total.',
    'fleet.terminalsTitle': 'Gares Routières & Quais Sécurisés',
    'fleet.terminalsDesc': 'Nos terminaux de Douala Akwa et Yaoundé Mvan offrent un accueil professionnel, des salles d\'attente confortables et des départs ponctuels.',

    // Footer
    'footer.brand': 'GLOBAL VOYAGES',
    'footer.desc': 'Société de transport interurbain et de logistique express au Cameroun. Fiabilité, ponctualité et confort au standard international.',
    'footer.stations': 'Gares & Terminaux',
    'footer.commitments': 'Nos Engagements',
    'footer.assistance': 'Service Client',
    'footer.punctuality': 'Départs à heures fixes garantis',
    'footer.safety': 'Sécurité et suivi GPS 24/7',
    'footer.comfort': 'Flotte VIP climatisée',
    'footer.parcels': 'Messagerie colis express sécurisée',
    'footer.phone': 'Douala: (+237) 670 00 00 01 | Yaoundé: (+237) 690 00 00 02',
    'footer.hours': 'Guichets ouverts 7j/7 de 05h30 à 21h30',
    'footer.legal': 'Tous droits réservés. Transport & Logistique Cameroun.',

    // Customer Portal
    'customer.badge': 'Portail Voyageur & Expéditeur',
    'customer.welcome': 'Bienvenue,',
    'customer.subtitle': 'Gérez vos réservations de tickets de bus et suivez l\'acheminement de vos colis en gare.',
    'customer.reportIssue': 'Signaler un Problème',
    'customer.tabParcels': 'Mes Colis Expédiés / Reçus',
    'customer.tabBookings': 'Mes Réservations & Billets',
    'customer.searchPlaceholder': 'Rechercher par bordereau...',
    'customer.loadingParcels': 'Chargement de vos colis...',
    'customer.noParcels': 'Aucun colis enregistré sous votre compte pour l\'instant.',
    'customer.trip': 'Trajet :',
    'customer.device': 'Dispositif :',
    'customer.iotActive': 'Balise IoT GPS Active',
    'customer.stationCheck': 'Contrôle en Gare',
    'customer.registeredOn': 'Enregistré le',
    'customer.publicView': 'Vue Suivi Public',
    'customer.originStation': 'Gare de Départ',
    'customer.destStation': 'Gare d\'Arrivée',
    'customer.gpsSignal': 'Signal GPS Télétransmis',
    'customer.battery': 'Batterie :',
    'customer.noIotDesc': 'Ce colis est acheminé avec validation physique à chaque checkpoint de gare.',
    'customer.selectParcelPrompt': 'Sélectionnez un colis dans la liste pour consulter les détails d\'acheminement.',
    'customer.tripsTitle': 'Mes Billets & Départs Disponibles',
    'customer.bookNewTicket': 'Réserver un Billet',
    'customer.confirmedTicket': 'Billet Confirmé & Payé',
    'customer.buyNewPrompt': 'Acheter un nouveau billet',
    'customer.buyNewDesc': 'Voyagez confortablement sur les lignes Global Voyages',
    'customer.availableTrips': 'Liaisons Programmées en Temps Réel',
    'customer.departure': 'Départ :',
    'customer.busNumber': 'Autocar N°',
    'customer.seatsLeft': 'places dispo',
    'customer.securePayment': 'Paiement Sécurisé CamPay',
    'customer.ticketAmount': 'Montant du titre de transport :',
    'customer.mobileMoneyLabel': 'Numéro Mobile Money (ex: 2376XXXXXXXX)',
    'customer.payValidate': 'Valider & Débiter',
    'customer.payProcessing': 'Initialisation...',
    'customer.paySuccess': 'Demande de paiement envoyée ! Veuillez confirmer sur votre mobile.',
    'customer.downloadPdf': 'PDF',
    'customer.passenger': 'Voyageur / Titulaire',

    // Map Component
    'map.gpsActive': 'GPS ACTIF',
    'map.speed': 'Vitesse',
    'map.battery': 'Batterie',
    'map.near': 'À prox. de :',
    'map.fullscreen': 'Plein Écran',
    'map.exitFullscreen': 'Quitter Plein Écran',
    'map.recenterBus': 'Centrer sur le Bus',
    'map.fullRoute': 'Vue Globale du Trajet',
    'map.zoomIn': 'Zoom Avant',
    'map.zoomOut': 'Zoom Arrière',
    'map.guideTitle': 'Guide des Endroits & Étapes de la Ligne',
    'map.steps': 'étapes',
    'map.guideHint': '• Cliquez sur une ville pour centrer la carte',
    'map.show': 'Afficher',
    'map.hide': 'Masquer',
    'map.view': 'Voir ➔',
    'map.layerRoad': 'Plan Routier (OSM)',
    'map.layerVoyager': 'CartoDB Voyager HD',
    'map.layerSatellite': 'Satellite HD',
    'map.layerDark': 'CartoDB Sombre',
    'map.statusPassed': '✓ Franchi',
    'map.statusCurrent': '📍 Position Bus',
    'map.statusUpcoming': '⏱️ À venir',
    'map.popupStatus': 'Statut autocar :',
    'map.popupPassed': '✓ Étape franchie',
    'map.popupCurrent': '📍 En approche immédiate',
    'map.popupUpcoming': '⏱️ Étape à venir',
    'map.originPrefix': '🏁 Départ :',
    'map.destPrefix': '🏁 Arrivée :',
    'map.busTitle': 'Position GPS Flotte en Direct',
    'map.busCurrentSpeed': 'Vitesse Actuelle',
    'map.busIotBattery': 'Batterie IoT',

    // Booking Flow Modal
    'booking.stepSchedule': '1. Horaires & Disponibilités',
    'booking.stepSeat': '2. Plan du Bus & Choix du Siège',
    'booking.stepPayment': '3. Paiement Sécurisé Mobile Money',
    'booking.stepSuccess': '✓ Titre de Transport Émis',
    'booking.step1': 'Horaires',
    'booking.step2': 'Choix du Siège',
    'booking.step3': 'Paiement',
    'booking.step4': 'Billet',
    'booking.origin': 'Gare de Départ',
    'booking.destination': 'Gare d\'Arrivée',
    'booking.date': 'Date de Voyage',
    'booking.availableDepartures': 'Départs disponibles ce jour :',
    'booking.scheduledTrips': 'voyages programmés',
    'booking.seatsAvailable': 'places disponibles',
    'booking.selectDeparture': 'Choisir ce départ',
    'booking.changeDeparture': 'Changer départ',
    'booking.fare': 'Tarif :',
    'booking.available': 'Libre',
    'booking.selected': 'Sélectionné',
    'booking.occupied': 'Occupé',
    'booking.driverCabin': 'Poste Chauffeur',
    'booking.door': 'Porte d\'accès',
    'booking.busRear': 'Arrière du Car VIP',
    'booking.yourSelection': 'Votre sélection :',
    'booking.firstClassFare': 'Tarif unique première classe :',
    'booking.back': 'Retour',
    'booking.continuePayment': 'Continuer vers le Paiement',
    'booking.passengerDetails': 'Informations Réservation & Passager',
    'booking.passengerName': 'Nom & Prénom du Voyageur',
    'booking.passengerNamePlaceholder': 'ex: Deborah Nakamura',
    'booking.cniLabel': 'Numéro CNI / Passeport (Embarquement)',
    'booking.cniPlaceholder': 'ex: 110293847',
    'booking.emailLabel': 'Email de confirmation (Billet PDF)',
    'booking.emailPlaceholder': 'ex: deborah@example.com',
    'booking.operatorLabel': 'Choisissez votre Opérateur Mobile Money',
    'booking.phoneLabel': 'Numéro de Téléphone Mobile Money',
    'booking.phoneHint': 'Entrez vos 9 chiffres (ex: 677 94 96 99). L\'indicatif +237 est géré automatiquement.',
    'booking.changeSeat': 'Modifier le Siège',
    'booking.confirmAndPay': 'Valider & Payer',
    'booking.sendingPush': 'Envoi de la demande CamPay...',
    'booking.pushSent': 'Demande de Paiement Transmise !',
    'booking.pushDesc': 'Un message push a été envoyé sur votre téléphone. Veuillez valider le débit avec votre code PIN secret.',
    'booking.actionRequired': 'Action requise sur votre mobile :',
    'booking.ussdHint': 'Si vous n\'avez pas reçu de popup automatique, composez directement le code USSD ci-dessous pour confirmer :',
    'booking.copy': 'Copier',
    'booking.copied': 'Copié !',
    'booking.ticketReserved': 'Billet Réservé',
    'booking.passengerReservation': 'Passager Titulaire (Réservation)',
    'booking.trip': 'Voyage',
    'booking.dateTime': 'Date & Heure',
    'booking.assignedSeat': 'Siège Attribué',
    'booking.amount': 'Montant',
    'booking.downloadTicket': 'Télécharger Billet',
    'booking.print': 'Imprimer',
    'booking.done': 'Terminer & Voir Billets',
    'booking.windowSeat': 'Fenêtre VIP',
    'booking.aisleSeat': 'Couloir VIP',

    // Driver Dashboard
    'driver.title': 'Console de Bord Chauffeur',
    'driver.captain': 'Capitaine',
    'driver.desc': 'Liaisons routières assignées, validation des départs/arrivées et signalement d\'incidents.',
    'driver.refresh': 'Actualiser les Voyages',
    'driver.assignedTrips': 'Vos Liaisons Assignées',
    'driver.confirmDeparture': 'Confirmer le Départ',
    'driver.confirmArrival': 'Confirmer l\'Arrivée',
    'driver.reportIncident': 'Signaler un Incident',
    'driver.routeMap': 'Carte de Navigation & Itinéraire en Direct',
    'driver.inTransit': 'En Route (Axe N3)',
    'driver.scheduled': 'Départ Programmé',
    'driver.completed': 'Voyage Terminé',
    'driver.noTrips': 'Aucune liaison assignée pour le moment.',

    // Parcel Agent Dashboard
    'agent.title': 'Console Agent de Fret & Colis',
    'agent.subtitle': 'Gestion des réceptions, affectation des balises IoT et résolution des réclamations.',
    'agent.tabParcels': 'Colis en Gare & Transit',
    'agent.tabIssues': 'Réclamations & Litiges',
    'agent.registerParcel': 'Enregistrer un Colis',
    'agent.assignTracker': 'Affecter Balise GPS',
    'agent.resolveIssue': 'Traiter Réclamation',
    'agent.searchPlaceholder': 'Rechercher par N° de suivi, expéditeur, destinataire...',
    'agent.inspectTitle': 'Inspection & Suivi Géolocalisé du Colis',
    'agent.statusLabel': 'Statut',
    'agent.origin': 'Gare Départ',
    'agent.destination': 'Gare Arrivée',
    'agent.weight': 'Poids',
    'agent.device': 'Balise',
    'agent.date': 'Date',
    'agent.actions': 'Actions',

    // Admin Dashboard
    'admin.badge': 'Portail d\'Administration Réseau & Flotte',
    'admin.title': 'Supervision Nationale & Logistique',
    'admin.subtitle': 'Gouvernance centralisée des gares routières, trajets de bus, comptes utilisateurs et télémétrie GPS en direct',
    'admin.refresh': 'Actualiser les données',
    'admin.kpiParcels': 'Total Colis Enregistrés',
    'admin.kpiTrackers': 'En Transit (Balises GPS)',
    'admin.kpiTrips': 'Voyages Actifs',
    'admin.kpiStations': 'Gares Connectées',
    'admin.kpiIssues': 'Litiges en Cours',
    'admin.tabMonitor': 'Carte de Télémétrie Flotte & Colis',
    'admin.tabUsers': 'Comptes Utilisateurs',
    'admin.tabStations': 'Gares Routières',
    'admin.tabRoutes': 'Lignes & Corridors',
    'admin.tabTrips': 'Voyages & Départs',
    'admin.tabIot': 'Parc Balises IoT',
    'admin.tabIssues': 'Réclamations & Incidents'
  },
  en: {
    // Navigation
    'nav.track': 'Tracking & Booking',
    'nav.fleet': 'Our Fleet',
    'nav.portal': 'Passenger Portal',
    'nav.reportIssue': 'Claims',
    'nav.login': 'Sign In',
    'nav.logout': 'Sign Out',
    'nav.role': 'Switch Profile',
    'nav.notifications': 'Notifications',
    'nav.switchRole': '1-Click Demo Access',
    'nav.deboraAdmin': 'Admin Debora',
    'nav.adminPortal': 'Admin Portal',
    'nav.agentDouala': 'Douala Agent',
    'nav.agentYaounde': 'Yaoundé Agent',
    'nav.driver': 'Bus Driver',
    'nav.customer': 'Customer (Alice)',

    // Auth Modal
    'auth.titleLogin': 'Member Sign In',
    'auth.titleRegister': 'Create an Account',
    'auth.identifier': 'Username or Email',
    'auth.identifierPlaceholder': 'e.g. debora or user@email.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': '••••••••',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'e.g. John Doe',
    'auth.phone': 'Phone Number (Optional)',
    'auth.btnLogin': 'Sign In Securely',
    'auth.btnRegister': 'Create Account',
    'auth.submitting': 'Authenticating...',
    'auth.quickAccess': '1-Click Demo Access',
    'auth.deboraHint': 'Configured Admin Account:',
    'auth.deboraBtn': '1-Click Sign In (debora)',

    // Hero & Search
    'hero.badge': 'National Transit Network',
    'hero.title': 'Travel and ship with complete peace of mind',
    'hero.subtitle': 'Daily express connections Douala ↔ Yaoundé and courier logistics monitored via direct GPS telemetry.',
    'tab.track': 'Track a Parcel',
    'tab.book': 'Search for Trips',
    'tab.map': 'Live Fleet & Places Map',
    'track.placeholder': 'Enter tracking number (e.g. GV-2026-9042)',
    'track.btn': 'Locate Parcel',
    'track.quickDemo': 'Recent examples:',
    'track.searching': 'Searching for parcel...',
    'track.refresh': 'Refresh',
    'track.copied': 'Copied!',
    'track.copy': 'Copy code',
    'book.origin': 'Origin Terminal',
    'book.destination': 'Destination Terminal',
    'book.date': 'Travel Date',
    'book.btn': 'Find Departures',
    'book.price': 'XAF',
    'book.reserve': 'Book Ticket',
    'book.seats': 'seats',
    'book.noTrips': 'No departures currently scheduled on this route.',
    'book.availableTrips': 'Available departures:',
    'book.directLink': 'Direct Route',
    'book.history': 'Transit Milestones History',

    // Tracking Board
    'status.origin': 'Origin Station',
    'status.transit': 'In Transit (Bus)',
    'status.destination': 'Destination Station',
    'status.speed': 'Speed',
    'status.battery': 'Tracker Battery',
    'status.sender': 'Sender',
    'status.recipient': 'Recipient',
    'status.weight': 'Weight',
    'status.lastPing': 'Updated',
    'status.incidentReported': 'Reported incident / delay:',
    'status.reportIssue': 'Report an issue with this parcel',

    // Fleet Showcase
    'fleet.title': 'Excellence in Intercity Travel',
    'fleet.subtitle': 'Modern luxury coaches meeting international standards and welcoming passenger terminals.',
    'fleet.vipTitle': 'First Class VIP Comfort',
    'fleet.vipDesc': 'Reclining leather armchairs, climate control, personal device charging, and air suspension for maximum rest.',
    'fleet.terminalsTitle': 'Modern Terminals & Secure Platforms',
    'fleet.terminalsDesc': 'Our Douala Akwa and Yaoundé Mvan hubs feature professional service, comfortable lounges, and strictly punctual departures.',

    // Footer
    'footer.brand': 'GLOBAL VOYAGES',
    'footer.desc': 'Premier intercity transit and express logistics company in Cameroon. Reliability, safety, and international comfort.',
    'footer.stations': 'Terminals & Hubs',
    'footer.commitments': 'Our Commitments',
    'footer.assistance': 'Customer Service',
    'footer.punctuality': 'Strictly punctual departure schedules',
    'footer.safety': 'Enhanced safety & 24/7 GPS tracking',
    'footer.comfort': 'Fully air-conditioned VIP coaches',
    'footer.parcels': 'Secure express parcel courier',
    'footer.phone': 'Douala: (+237) 670 00 00 01 | Yaoundé: (+237) 690 00 00 02',
    'footer.hours': 'Ticketing open daily from 5:30 AM to 9:30 PM',
    'footer.legal': 'All rights reserved. Cameroon Transit & Logistics.',

    // Customer Portal
    'customer.badge': 'Passenger & Shipper Portal',
    'customer.welcome': 'Welcome,',
    'customer.subtitle': 'Manage your bus ticket bookings and track your station-to-station parcels in real time.',
    'customer.reportIssue': 'Report an Issue',
    'customer.tabParcels': 'My Shipped / Received Parcels',
    'customer.tabBookings': 'My Bookings & Tickets',
    'customer.searchPlaceholder': 'Search by tracking number...',
    'customer.loadingParcels': 'Loading your parcels...',
    'customer.noParcels': 'No parcels registered under your account yet.',
    'customer.trip': 'Route:',
    'customer.device': 'Tracking Device:',
    'customer.iotActive': 'Active IoT GPS Tracker',
    'customer.stationCheck': 'Station Physical Check',
    'customer.registeredOn': 'Registered on',
    'customer.publicView': 'Public Tracking View',
    'customer.originStation': 'Origin Station',
    'customer.destStation': 'Destination Station',
    'customer.gpsSignal': 'Live GPS Signal Transmitted',
    'customer.battery': 'Battery:',
    'customer.noIotDesc': 'This parcel is routed with physical inspection checkpoints at each station.',
    'customer.selectParcelPrompt': 'Select a parcel from the list to view live tracking details.',
    'customer.tripsTitle': 'My Tickets & Available Departures',
    'customer.bookNewTicket': 'Book a Ticket',
    'customer.confirmedTicket': 'Ticket Confirmed & Paid',
    'customer.buyNewPrompt': 'Book a new departure',
    'customer.buyNewDesc': 'Travel in first-class comfort across Cameroon with Global Voyages',
    'customer.availableTrips': 'Live Scheduled Departures',
    'customer.departure': 'Departure:',
    'customer.busNumber': 'Coach No.',
    'customer.seatsLeft': 'seats left',
    'customer.securePayment': 'Secure CamPay Payment',
    'customer.ticketAmount': 'Ticket amount:',
    'customer.mobileMoneyLabel': 'Mobile Money Number (e.g. 2376XXXXXXXX)',
    'customer.payValidate': 'Confirm & Charge',
    'customer.payProcessing': 'Processing...',
    'customer.paySuccess': 'Payment request sent! Please approve the push prompt on your mobile.',
    'customer.downloadPdf': 'PDF',
    'customer.passenger': 'Passenger / Ticket Holder',

    // Map Component
    'map.gpsActive': 'LIVE GPS',
    'map.speed': 'Speed',
    'map.battery': 'Battery',
    'map.near': 'Near:',
    'map.fullscreen': 'Full Screen',
    'map.exitFullscreen': 'Exit Full Screen',
    'map.recenterBus': 'Recenter on Live Bus',
    'map.fullRoute': 'Full Route View',
    'map.zoomIn': 'Zoom In',
    'map.zoomOut': 'Zoom Out',
    'map.guideTitle': 'Waypoints & Route Milestones Guide',
    'map.steps': 'steps',
    'map.guideHint': '• Click a waypoint to center map',
    'map.show': 'Show',
    'map.hide': 'Hide',
    'map.view': 'View ➔',
    'map.layerRoad': 'Road Map (OSM)',
    'map.layerVoyager': 'CartoDB Voyager HD',
    'map.layerSatellite': 'Satellite HD',
    'map.layerDark': 'CartoDB Dark',
    'map.statusPassed': '✓ Passed',
    'map.statusCurrent': '📍 Bus Location',
    'map.statusUpcoming': '⏱️ Upcoming',
    'map.popupStatus': 'Coach Status:',
    'map.popupPassed': '✓ Milestone Passed',
    'map.popupCurrent': '📍 Approaching Now',
    'map.popupUpcoming': '⏱️ Upcoming Stop',
    'map.originPrefix': '🏁 Origin:',
    'map.destPrefix': '🏁 Destination:',
    'map.busTitle': 'Fleet Live GPS Telemetry',
    'map.busCurrentSpeed': 'Current Speed',
    'map.busIotBattery': 'IoT Battery',

    // Booking Flow Modal
    'booking.stepSchedule': '1. Timetable & Availability',
    'booking.stepSeat': '2. Coach Map & Seat Selection',
    'booking.stepPayment': '3. Secure Mobile Money Payment',
    'booking.stepSuccess': '✓ Boarding Pass Issued',
    'booking.step1': 'Timetable',
    'booking.step2': 'Seat Selection',
    'booking.step3': 'Payment',
    'booking.step4': 'Ticket',
    'booking.origin': 'Departure Station',
    'booking.destination': 'Arrival Station',
    'booking.date': 'Travel Date',
    'booking.availableDepartures': 'Available departures today:',
    'booking.scheduledTrips': 'scheduled trips',
    'booking.seatsAvailable': 'seats available',
    'booking.selectDeparture': 'Select Departure',
    'booking.changeDeparture': 'Change time',
    'booking.fare': 'Fare:',
    'booking.available': 'Available',
    'booking.selected': 'Selected',
    'booking.occupied': 'Occupied',
    'booking.driverCabin': 'Driver Cockpit',
    'booking.door': 'Access Door',
    'booking.busRear': 'Rear of VIP Coach',
    'booking.yourSelection': 'Your selection:',
    'booking.firstClassFare': 'First class fare:',
    'booking.back': 'Back',
    'booking.continuePayment': 'Continue to Payment',
    'booking.passengerDetails': 'Passenger & Reservation Details',
    'booking.passengerName': 'Full Passenger Name',
    'booking.passengerNamePlaceholder': 'e.g. Deborah Nakamura',
    'booking.cniLabel': 'National ID / Passport Number',
    'booking.cniPlaceholder': 'e.g. 110293847',
    'booking.emailLabel': 'Confirmation Email (PDF Ticket)',
    'booking.emailPlaceholder': 'e.g. deborah@example.com',
    'booking.operatorLabel': 'Choose Mobile Money Operator',
    'booking.phoneLabel': 'Mobile Money Phone Number',
    'booking.phoneHint': 'Enter 9 digits (e.g. 677 94 96 99). Country code +237 is added automatically.',
    'booking.changeSeat': 'Change Seat',
    'booking.confirmAndPay': 'Confirm & Pay',
    'booking.sendingPush': 'Sending CamPay Push...',
    'booking.pushSent': 'Payment Push Notification Sent!',
    'booking.pushDesc': 'A push notification was sent to your mobile. Please approve the charge using your secret PIN.',
    'booking.actionRequired': 'Action required on your phone:',
    'booking.ussdHint': 'If you didn\'t receive an automated prompt, dial the USSD code below to confirm:',
    'booking.copy': 'Copy',
    'booking.copied': 'Copied!',
    'booking.ticketReserved': 'Ticket Reserved',
    'booking.passengerReservation': 'Passenger Name (Reservation)',
    'booking.trip': 'Trip',
    'booking.dateTime': 'Date & Time',
    'booking.assignedSeat': 'Chosen Seat',
    'booking.amount': 'Amount',
    'booking.downloadTicket': 'Download Ticket',
    'booking.print': 'Print',
    'booking.done': 'Done & View Tickets',
    'booking.windowSeat': 'Window VIP',
    'booking.aisleSeat': 'Aisle VIP',

    // Driver Dashboard
    'driver.title': 'Driver Flight Deck',
    'driver.captain': 'Captain',
    'driver.desc': 'Assigned highway routes, departure/arrival confirmation and safety incident reporting.',
    'driver.refresh': 'Refresh Trips',
    'driver.assignedTrips': 'Your Assigned Trips',
    'driver.confirmDeparture': 'Confirm Departure',
    'driver.confirmArrival': 'Confirm Arrival',
    'driver.reportIncident': 'Report Incident',
    'driver.routeMap': 'Live Navigation Map & Waypoints',
    'driver.inTransit': 'On Route (Axe N3)',
    'driver.scheduled': 'Scheduled Departure',
    'driver.completed': 'Completed Trip',
    'driver.noTrips': 'No trips assigned at the moment.',

    // Parcel Agent Dashboard
    'agent.title': 'Freight & Parcel Station Console',
    'agent.subtitle': 'Manage station intake, assign IoT GPS trackers, and resolve parcel claims.',
    'agent.tabParcels': 'Parcels at Station & In Transit',
    'agent.tabIssues': 'Claims & Incident Tickets',
    'agent.registerParcel': 'Register New Parcel',
    'agent.assignTracker': 'Assign GPS Tracker',
    'agent.resolveIssue': 'Resolve Claim',
    'agent.searchPlaceholder': 'Search by tracking number, sender, receiver...',
    'agent.inspectTitle': 'Live Parcel Inspection & GPS Map',
    'agent.statusLabel': 'Status',
    'agent.origin': 'Origin Station',
    'agent.destination': 'Destination Station',
    'agent.weight': 'Weight',
    'agent.device': 'Device',
    'agent.date': 'Date',
    'agent.actions': 'Actions',

    // Admin Dashboard
    'admin.badge': 'Network & Fleet Administration Portal',
    'admin.title': 'National Supervision & Logistics',
    'admin.subtitle': 'Centralized governance for bus terminals, trips, user accounts, and direct IoT telemetry',
    'admin.refresh': 'Refresh Data',
    'admin.kpiParcels': 'Total Registered Parcels',
    'admin.kpiTrackers': 'In Transit (IoT Trackers)',
    'admin.kpiTrips': 'Active Scheduled Trips',
    'admin.kpiStations': 'Connected Terminals',
    'admin.kpiIssues': 'Open Claims & Issues',
    'admin.tabMonitor': 'Fleet & Cargo Telemetry Map',
    'admin.tabUsers': 'User Accounts',
    'admin.tabStations': 'Bus Terminals',
    'admin.tabRoutes': 'Routes & Corridors',
    'admin.tabTrips': 'Trips & Departures',
    'admin.tabIot': 'IoT GPS Device Fleet',
    'admin.tabIssues': 'Claims & Incidents'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('gv_lang_v3');
    if (saved) return saved;
    // Default primary language is English
    localStorage.setItem('gv_lang_v3', 'en');
    localStorage.setItem('gv_lang', 'en');
    return 'en';
  });

  const setLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('gv_lang_v3', newLang);
    localStorage.setItem('gv_lang', newLang);
  };

  const toggleLanguage = () => {
    const nextLang = lang === 'en' ? 'fr' : 'en';
    setLanguage(nextLang);
  };

  const t = (key, fallback = '') => {
    const dict = translations[lang] || translations.en;
    return dict[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
