<?php
// PHP-App/src/Language.php
require_once __DIR__ . '/../config/config.php';

class Language {
    private static array $translations = [
        'fr' => [
            // Nav & Brand
            'brand.name' => 'GLOBAL VOYAGES',
            'brand.tagline' => 'Autocars VIP & Messagerie Express',
            'brand.sub' => 'VIP Intercity & Cargo',
            'nav.routes' => 'Lignes & Horaires',
            'nav.tracking' => 'Suivi Colis & IoT',
            'nav.fleet' => 'Flotte VIP',
            'nav.book' => 'Réserver Billet',
            'nav.login' => 'Connexion',
            'nav.myAccount' => 'Tableau de Bord',
            'nav.logout' => 'Déconnexion',

            // Hero
            'hero.badge' => 'RÉSEAU INTERURBAIN CAMEROUN • AXE LOURD N3',
            'hero.title' => 'Voyagez & Expédiez en Toute Sérénité',
            'hero.subtitle' => 'Liaisons quotidiennes VIP directes entre Douala et Yaoundé sur l\'Axe Lourd N3. Télémétrie IoT 4G et paiement sécurisé.',
            'hero.tabTrack' => 'Suivi Colis',
            'hero.tabBook' => 'Acheter un Billet',
            'hero.tabMap' => 'Carte Flotte',
            'hero.securityBadge' => 'Flotte VIP climatisée • Paiement CamPay sécurisé',
            'hero.filter' => 'Filtrer',
            'hero.instantDemo' => 'Démo instantanée :',

            // Search & Departures
            'search.origin' => 'Gare Départ',
            'search.destination' => 'Gare Destination',
            'search.date' => 'Date de Voyage',
            'search.today' => "Aujourd'hui",
            'search.tomorrow' => 'Demain',
            'search.btn' => 'Rechercher Départs',
            'search.departuresTitle' => 'Départs Programmés en Temps Réel',
            'search.selectedDate' => 'Date sélectionnée :',
            'search.directInfo' => 'Liaisons directes avec autocars VIP',
            'search.reserveOther' => 'Réserver Autre Date',
            'search.seatsLeft' => 'places VIP disponibles',
            'search.reserve' => 'Réserver Siège VIP',
            'search.price' => 'FCFA',
            'search.perPassenger' => 'par voyageur',
            'search.departure' => 'Départ :',
            'search.scheduled' => 'Programmé',
            'search.confirmed' => 'Confirmé',

            // Tracking
            'track.title' => 'Suivi d\'Acheminement Colis',
            'track.subtitle' => 'Télémétrie GPS et traçabilité aux checkpoints de gare',
            'track.placeholder' => 'Entrez le numéro (ex: PAR-2026-00125)',
            'track.btn' => 'Localiser',
            'track.status' => 'Statut de l\'Acheminement',
            'track.history' => 'Chronologie des Événements',
            'track.notFound' => 'Colis introuvable pour la référence',
            'track.notFoundHelp' => 'Vérifiez l\'orthographe de votre numéro d\'expédition.',
            'track.senderStation' => 'Gare Expéditrice',
            'track.destStation' => 'Gare Destinataire',
            'track.trackingNum' => 'Numéro de Suivi',
            'track.activeTracker' => 'Balise GPS 4G active sur le convoi',
            'track.seeMap' => '🗺️ Voir sur la Carte (See on Map)',

            // Live Map
            'map.title' => 'Liaison Interurbaine Axe Lourd N3 • Télémétrie 4G en Direct (Carto HD)',
            'map.subtitle' => 'Douala (Akwa) ↔ Yaoundé (Mvan) • Suivi des autocars et colis',
            'map.seeOnMap' => '🗺️ Voir sur la Carte (See on Map)',
            'map.hideMap' => 'Masquer la Carte / Hide Map',
            'map.speed' => 'Vitesse :',
            'map.stop' => 'Étape :',
            'map.close' => 'Fermer la Carte',

            // VIP Fleet Showcase
            'fleet.badge' => 'Confort Première Classe',
            'fleet.title' => 'Voyagez dans le Plus Grand Confort Interurbain',
            'fleet.desc' => 'Fauteuils en cuir inclinables, climatisation régulée et wifi 4G à bord sur toutes nos liaisons quotidiennes directes.',
            'fleet.punctuality' => 'Ponctualité 100%',
            'fleet.salons' => 'Salons VIP climatisés',
            'fleet.secureCargo' => 'Soute à bagages sécurisée',
            'fleet.security247' => 'Sécurité 24/7 sur quai',

            // Booking Modal & JS Wizard
            'booking.title' => 'Réservation de Billet VIP',
            'booking.subtitle' => 'Global Voyages VIP Intercity Express',
            'booking.step1' => '1. Horaires & Départs',
            'booking.step2' => '2. Choix du Siège',
            'booking.step3' => '3. Coordonnées & Paiement',
            'booking.step4' => '4. Validation Mobile USSD',
            'booking.step5' => '✓ Titre Émis',
            'booking.busFront' => '🚗 Avant du Bus / Chauffeur',
            'booking.vipDoor' => '🚪 Porte VIP',
            'booking.aisle' => 'ALLÉE',
            'booking.selectedSeat' => 'Siège Sélectionné',
            'booking.seatVIP' => 'Siège N° %s (VIP)',
            'booking.seatFree' => 'Siège %s Libre',
            'booking.seatOccupied' => 'Siège Occupé',
            'booking.ticketPrice' => 'Tarif Billet',
            'booking.back' => 'Retour',
            'booking.continueToPay' => 'Continuer vers Paiement ➔',
            'booking.passengerInfo' => 'Coordonnées du Passager Titulaire',
            'booking.passengerName' => 'Nom et Prénom *',
            'booking.passengerId' => 'N° CNI ou Passeport',
            'booking.phone' => 'Numéro Mobile Money (9 chiffres)',
            'booking.email' => 'Adresse Email (Optionnel)',
            'booking.operator' => 'Opérateur Mobile Money',
            'booking.phoneHelp' => 'L\'indicatif +237 est géré automatiquement.',
            'booking.payBtn' => 'Payer 5 000 FCFA avec CamPay',
            'booking.loadingDepartures' => 'Recherche des départs en temps réel...',
            'booking.noDepartures' => 'Aucun départ programmé sur cette ligne pour le %s.',
            'booking.seeTomorrow' => 'Voir les départs de demain',
            'booking.chooseSeat' => 'Choisir Siège ➔',
            'booking.connectingCampay' => 'Connexion CamPay...',
            'booking.pendingTitle' => 'Demande de Débit Transmise à CamPay !',
            'booking.pendingDesc' => 'Un message de confirmation push a été envoyé sur votre mobile. Veuillez valider le débit avec votre code PIN secret.',
            'booking.actionRequired' => 'Action Requise sur Mobile :',
            'booking.ussdHelp' => 'Si le popup ne s\'affiche pas, composez directement le code USSD ci-dessous :',
            'booking.ticketBlockedHelp' => '⏳ Le billet électronique ne peut être téléchargé qu\'après validation du débit par l\'opérateur.',
            'booking.checkStatus' => 'Vérifier le Statut du Paiement',
            'booking.autoDetecting' => 'Détection automatique du paiement mobile en cours...',
            'booking.verifyingPayment' => 'Vérification de la validation CamPay...',
            'booking.demoConfirm' => "Détection automatique en cours...",
            'booking.successTitle' => 'Paiement Confirmé & Billet Validé !',
            'booking.successDesc' => 'Votre réservation est enregistrée de façon permanente dans notre base de données. Bon voyage avec Global Voyages !',
            'booking.paidTicket' => '✓ Titre de Transport Payé',
            'booking.downloadTicket' => 'Télécharger Billet (HTML / PDF)',
            'booking.close' => 'Terminer & Voir mes Billets',

            // Customer Dashboard
            'customer.vipWelcome' => 'Espace Voyageur VIP',
            'customer.newTicket' => 'Nouveau Billet',
            'customer.reportIssue' => 'Signaler un Problème',
            'customer.tabTickets' => 'Mes Billets de Voyage',
            'customer.tabParcels' => 'Mes Colis / Bagages',
            'customer.tabNotifications' => 'Notifications',
            'customer.tabIssues' => 'Mes Réclamations',
            'customer.paid' => 'Billet Validé & Payé',
            'customer.pending' => 'En Attente de Paiement',
            'customer.cancelled' => 'Réservation Annulée',
            'customer.passenger' => 'Passager',
            'customer.cancel' => 'Annuler',
            'customer.pay' => 'Payer OM/MoMo',
            'customer.ticket' => 'Billet 🖨️',
            'customer.track' => 'Suivre ➔',
            'customer.waybill' => 'Bordereau 🖨️',
            'customer.noTickets' => 'Aucun billet réservé pour le moment',
            'customer.buyNow' => 'Acheter un billet maintenant',
            'customer.noParcels' => 'Aucun colis enregistré pour le moment',
            'customer.noIssues' => 'Aucune réclamation signalée.',
            'customer.newReport' => 'Nouveau Signalement',
            'customer.close' => 'Fermer',

            // Footer
            'footer.tagline' => 'Réseau interurbain de première classe au Cameroun. Flotte d\'autocars VIP géolocalisés en temps réel et acheminement sécurisé de colis.',
            'footer.mainRoutes' => 'Lignes Principales',
            'footer.routeDlaYao' => 'Douala (Akwa) ➔ Yaoundé (Mvan) Express N3',
            'footer.routeYaoDla' => 'Yaoundé (Mvan) ➔ Douala (Akwa) Express N3',
            'footer.departuresFreq' => 'Départs quotidiens toutes les 2h30',
            'footer.escaleBoum' => 'Étape gastronomique Boumnyébel',
            'footer.securePayment' => 'Paiement Sécurisé',
            'footer.campayDesc' => 'Règlements instantanés par MTN Mobile Money (*126#) et Orange Money (#150*50#).',
            'footer.support' => 'Assistance 24/7',
            'footer.customerService' => 'Service Client & Bagages :',
            'footer.copyright' => 'Tous droits réservés.',

            // Roles
            'role.admin' => 'Administrateur',
            'role.driver' => 'Chauffeur',
            'role.booking_agent' => 'Agent Réservations',
            'role.parcel_agent' => 'Agent Colis',
            'role.customer' => 'Client Voyageur',

            // Login
            'login.title' => 'Connexion Sécurisée',
            'login.subtitle' => 'Accédez à votre espace Global Voyages',
            'login.demoQuick' => 'Accès Démo Instantané (1 Clic)',
            'login.orCredentials' => 'ou par identifiant',
            'login.username' => 'Identifiant ou Email',
            'login.password' => 'Mot de passe',
            'login.submit' => 'Se Connecter',
            'login.invalid' => 'Identifiants invalides.',

            // Waybill
            'waybill.title' => "Bordereau d'Expédition Colis",
            'waybill.badge' => "BORDEREAU D'EXPÉDITION",
            'waybill.origin' => 'Gare de Dépôt',
            'waybill.dest' => 'Gare de Destination',
            'waybill.sender' => 'Expéditeur',
            'waybill.recipient' => 'Destinataire',
            'waybill.weight' => 'Poids & Volume',
            'waybill.fees' => 'Frais :',
            'waybill.declaredValue' => 'Valeur Déclarée',
            'waybill.insurance' => 'Assurance Fret VIP incluse',
            'waybill.content' => 'Contenu / Description',
            'waybill.standardParcel' => 'Colis standard',
            'waybill.tracker' => 'Traceur IoT GPS',
            'waybill.unassigned' => 'Non assigné',
            'waybill.trackingNum' => 'Numéro de Suivi Colis',
            'waybill.status' => 'Statut :',
            'waybill.senderSig' => 'Signature Expéditeur :',
            'waybill.agentSig' => 'Visa & Cachet Agent Guichet :',
            'waybill.notice' => 'Présentez ce bordereau ou le numéro de suivi pour le retrait du colis.',
            'waybill.print' => "🖨️ Imprimer le Bordereau d'Expédition",

            // Agent
            'agent.bookingDesk' => 'Guichet Réservations & Bagages VIP',
            'agent.parcelDesk' => 'Guichet Fret, Colis & Messagerie',
            'agent.operationalMgmt' => 'Douala (Akwa) ↔ Yaoundé (Mvan) • Gestion Opérationnelle',
            'agent.newParcel' => 'Nouveau Colis',
            'agent.tabParcels' => '📦 Espace Agent de Colis',
            'agent.tabBookings' => '🎫 Espace Agent de Réservation',
            'agent.parcelsTitle' => 'Gestion des Expéditions de Colis & Fret',
            'agent.parcelsSub' => "Enregistrement, Pesée, Checkpoints et Journal d'Audit",
            'agent.searchPlaceholder' => 'Rechercher par n° de suivi, expéditeur...',
            'agent.colNumber' => 'Numéro',
            'agent.colSender' => 'Expéditeur',
            'agent.colRecipient' => 'Destinataire',
            'agent.colRoute' => 'Ligne',
            'agent.colWeightFees' => 'Poids / Frais',
            'agent.colTracker' => 'Traceur IoT',
            'agent.colStatus' => 'Statut',
            'agent.colActions' => 'Actions',
            'agent.none' => 'Aucun',
            'agent.btnStatus' => 'Statut ⚙️',
            'agent.btnHistory' => 'Historique 📜',
            'agent.btnWaybill' => 'Bordereau 🖨️',
            'agent.bookingsTitle' => 'Gestion des Réservations & Attribution IoT Bagage',
            'agent.bookingsSub' => 'Superviser les passagers, valider les encaissements guichet et lier un traceur physique au bagage',
            'agent.colRef' => 'Référence',
            'agent.colPassenger' => 'Passager (Profil)',
            'agent.colTrip' => 'Trajet',
            'agent.colSeat' => 'Siège VIP',
            'agent.colDateTime' => 'Date & Heure',
            'agent.colLuggageTracker' => 'Traceur IoT Bagage',
            'agent.colPayment' => 'Paiement',
            'agent.colDeskActions' => 'Actions Guichet',
            'agent.unassigned' => 'Non assigné',
            'agent.btnLinkTracker' => 'Lier Traceur IoT 🏷️',
            'agent.btnDeskCollect' => 'Encaisser Guichet',
            'agent.btnTicket' => 'Billet 🖨️',
            'agent.modalAssignTitle' => 'Assigner un Appareil IoT au Bagage',
            'agent.modalAssignSub' => 'Sélectionner la Balise IoT Physique à Fixer *',
            'agent.btnCancel' => 'Annuler',
            'agent.btnAttach' => 'Associer au Bagage',
            'agent.modalHistoryTitle' => "Historique d'Acheminement du Colis",
            'agent.noHistory' => 'Aucune étape enregistrée pour le moment.',
            'agent.btnClose' => 'Fermer',
            'agent.modalStatusTitle' => 'Actualiser le Statut du Colis',
            'agent.colisConcerned' => 'Colis Concerné',
            'agent.newStatusLabel' => "Nouveau Statut d'Acheminement",
            'agent.currentStationLabel' => 'Gare / Checkpoint Actuel',
            'agent.notesLabel' => 'Notes & Observations Checkpoint',
            'agent.notesPlaceholder' => 'Ex: Colis inspecté, scellé intact, chargé dans soute VIP...',
            'agent.btnSaveStatus' => 'Enregistrer Statut',
            'agent.modalRegisterTitle' => 'Enregistrer un Colis au Guichet',
            'agent.senderName' => 'Expéditeur (Nom) *',
            'agent.senderPhone' => 'Téléphone Expéditeur *',
            'agent.recipientName' => 'Destinataire (Nom) *',
            'agent.recipientPhone' => 'Téléphone Destinataire *',
            'agent.recipientAddress' => 'Adresse / Quartier de Livraison *',
            'agent.originStation' => 'Gare Départ',
            'agent.destStation' => 'Gare Arrivée',
            'agent.weightKg' => 'Poids (kg) *',
            'agent.shippingFee' => "Frais d'Expédition (500 F/kg)",
            'agent.declaredValue' => 'Valeur Déclarée (FCFA)',
            'agent.trackerSelect' => 'Traceur IoT Fixé',
            'agent.trackerNone' => 'Aucun (Traceur standard)',
            'agent.description' => 'Description du Contenu',
            'agent.descriptionPlaceholder' => 'Ex: Documents juridiques, pièces détachées, effets personnels...',
            'agent.btnRegisterSubmit' => 'Enregistrer & Émettre Bordereau',

            // Admin
            'admin.bannerTitle' => 'Supervision Centrale & Administration',
            'admin.bannerSubtitle' => 'Contrôle des Utilisateurs, Traceurs IoT, Départs Douala ↔ Yaoundé & Billetterie',
            'admin.newTrip' => 'Nouveau Départ',
            'admin.kpiRevenue' => "Chiffre d'Affaires",
            'admin.kpiBookings' => 'Billets Réservés',
            'admin.kpiParcels' => 'Colis & Fret',
            'admin.kpiTrips' => 'Départs Ligne N3',
            'admin.kpiUsers' => 'Comptes Utilisateurs',
            'admin.kpiTrackers' => 'Traceurs IoT 4G',
            'admin.tabUsers' => 'Comptes Utilisateurs',
            'admin.tabIoT' => 'Appareils IoT',
            'admin.tabBookings' => 'Réservations Billets',
            'admin.tabTrips' => 'Départs Programmés',
            'admin.tabParcels' => 'Fret & Colis',
            'admin.usersTitle' => 'Gestion des Comptes Acteurs (Admin, Agents, Chauffeurs, Clients)',
            'admin.usersSub' => 'Mettre à jour, bannir/débannir ou supprimer un compte',
            'admin.colId' => 'ID',
            'admin.colFullName' => 'Nom Complet',
            'admin.colUsername' => 'Identifiant / Email',
            'admin.colPhone' => 'Téléphone',
            'admin.colRole' => 'Rôle',
            'admin.colStatus' => 'Statut',
            'admin.colActions' => 'Actions',
            'admin.statusBanned' => 'BANNI / SUSPENDU',
            'admin.statusActive' => 'ACTIF',
            'admin.btnEdit' => 'Modifier ✏️',
            'admin.btnBan' => 'Bannir',
            'admin.btnUnban' => 'Réactiver',
            'admin.btnDelete' => 'Supprimer 🗑️',
            'admin.iotTitle' => 'Flotte de Balises & Traceurs IoT 4G (Axe N3)',
            'admin.iotSub' => 'Superviser l’état des batteries, les coordonnées GPS et assigner aux convois',
            'admin.btnAddTracker' => '+ Ajouter un Traceur',
            'admin.colTrackerCode' => 'Code Traceur',
            'admin.colModel' => 'Modèle Matériel',
            'admin.colBattery' => 'Batterie',
            'admin.colGpsPos' => 'Dernière Position GPS',
            'admin.colSpeed' => 'Vitesse',
            'admin.statusAvailable' => 'DISPONIBLE',
            'admin.statusAssigned' => 'ASSIGNÉ',
            'admin.statusMaintenance' => 'MAINTENANCE',
            'admin.tripsTitle' => 'Gestion des Départs Interurbains Ligne N3',
            'admin.tripsSub' => 'Programmation quotidienne des départs directs Douala ↔ Yaoundé',
            'admin.colTripNum' => 'N° Voyage',
            'admin.colLine' => 'Ligne',
            'admin.colBus' => 'Autocar VIP',
            'admin.colDriver' => 'Chauffeur',
            'admin.colDeparture' => 'Départ Prévu',
            'admin.colArrival' => 'Arrivée Estimée',
            'admin.colFare' => 'Tarif',
            'admin.unassignedDriver' => 'Non assigné',

            // Driver
            'driver.deckTitle' => 'Cockpit Chauffeur • Axe Lourd N3 Douala ↔ Yaoundé',
            'driver.deckSub' => 'Télémétrie GPS 4G • Scania VIP First Class',
            'driver.gpsOnline' => 'GPS En Ligne (Batterie: %s%%)',
            'driver.navTitle' => 'Itinéraire N3 en Direct • Douala ↔ Yaoundé (Carto HD)',
            'driver.assignedTrips' => 'Trajets Douala ↔ Yaoundé Assignés',
            'driver.coach' => 'Autocar VIP',
            'driver.scheduledDep' => 'Départ Prévu',
            'driver.scheduledArr' => 'Arrivée Estimée',
            'driver.btnDepart' => 'Confirmer Départ 🚀',
            'driver.btnArrive' => 'Confirmer Arrivée 🏁',
            'driver.updateGpsStop' => 'Mise à Jour Étape GPS / Arrêt N3',
            'driver.currentSpeed' => 'Vitesse Actuelle (km/h)',
            'driver.btnUpdatePosition' => 'Actualiser Position GPS',
            'driver.reportIncident' => 'Rapport de Trajet / Incident Ligne',
            'driver.btnTransmitReport' => 'Transmettre Rapport',
        ],
        'en' => [
            // Nav & Brand
            'brand.name' => 'GLOBAL VOYAGES',
            'brand.tagline' => 'VIP Coaches & Express Parcel Logistics',
            'brand.sub' => 'VIP Intercity & Cargo',
            'nav.routes' => 'Routes & Schedules',
            'nav.tracking' => 'Parcel & IoT Tracking',
            'nav.fleet' => 'VIP Fleet',
            'nav.book' => 'Book Ticket',
            'nav.login' => 'Sign In',
            'nav.myAccount' => 'Dashboard',
            'nav.logout' => 'Sign Out',

            // Hero
            'hero.badge' => 'CAMEROON INTERCITY NETWORK • HIGHWAY N3',
            'hero.title' => 'Travel & Ship with Complete Peace of Mind',
            'hero.subtitle' => 'Direct first-class VIP intercity connections between Douala and Yaounde along Highway N3. Live 4G IoT telemetry and secure mobile payment.',
            'hero.tabTrack' => 'Track Parcel',
            'hero.tabBook' => 'Book Bus Ticket',
            'hero.tabMap' => 'Fleet Map',
            'hero.securityBadge' => 'Air-conditioned VIP Fleet • Secure CamPay Mobile Pay',
            'hero.filter' => 'Filter',
            'hero.instantDemo' => 'Instant demo:',

            // Search & Departures
            'search.origin' => 'Departure Station',
            'search.destination' => 'Arrival Station',
            'search.date' => 'Travel Date',
            'search.today' => 'Today',
            'search.tomorrow' => 'Tomorrow',
            'search.btn' => 'Find Departures',
            'search.departuresTitle' => 'Live Scheduled Departures',
            'search.selectedDate' => 'Selected date:',
            'search.directInfo' => 'Direct non-stop service with VIP coaches',
            'search.reserveOther' => 'Book Another Date',
            'search.seatsLeft' => 'VIP seats available',
            'search.reserve' => 'Reserve VIP Seat',
            'search.price' => 'XAF',
            'search.perPassenger' => 'per traveler',
            'search.departure' => 'Departure:',
            'search.scheduled' => 'Scheduled',
            'search.confirmed' => 'Confirmed',

            // Tracking
            'track.title' => 'Parcel Shipment Tracking',
            'track.subtitle' => 'Live GPS telemetry and terminal checkpoint tracking',
            'track.placeholder' => 'Enter tracking reference (e.g. PAR-2026-00125)',
            'track.btn' => 'Locate',
            'track.status' => 'Shipment Status',
            'track.history' => 'Event Timeline',
            'track.notFound' => 'Parcel not found for reference',
            'track.notFoundHelp' => 'Please verify the spelling of your tracking reference.',
            'track.senderStation' => 'Origin Station',
            'track.destStation' => 'Destination Station',
            'track.trackingNum' => 'Tracking Number',
            'track.activeTracker' => '4G GPS tracker active on convoy',
            'track.seeMap' => '🗺️ See on Map',

            // Live Map
            'map.title' => 'Intercity Highway N3 Corridor • Live 4G Telemetry (Carto HD)',
            'map.subtitle' => 'Douala (Akwa) ↔ Yaounde (Mvan) • Live coach and baggage tracking',
            'map.seeOnMap' => '🗺️ See on Map',
            'map.hideMap' => 'Hide Map',
            'map.speed' => 'Speed:',
            'map.stop' => 'Current Stop:',
            'map.close' => 'Close Map',

            // VIP Fleet Showcase
            'fleet.badge' => 'First Class Comfort',
            'fleet.title' => 'Travel in Utmost Intercity Comfort',
            'fleet.desc' => 'Reclining leather seats, regulated air conditioning and high-speed 4G Wi-Fi onboard all our direct daily services.',
            'fleet.punctuality' => '100% Punctuality',
            'fleet.salons' => 'Air-conditioned VIP Lounges',
            'fleet.secureCargo' => 'Secure luggage hold',
            'fleet.security247' => '24/7 Platform Security',

            // Booking Modal & JS Wizard
            'booking.title' => 'VIP Ticket Booking',
            'booking.subtitle' => 'Global Voyages VIP Intercity Express',
            'booking.step1' => '1. Schedules & Departures',
            'booking.step2' => '2. Seat Selection',
            'booking.step3' => '3. Passenger & Payment',
            'booking.step4' => '4. Mobile USSD Authorization',
            'booking.step5' => '✓ Ticket Issued',
            'booking.busFront' => '🚗 Front of Bus / Driver',
            'booking.vipDoor' => '🚪 VIP Door',
            'booking.aisle' => 'AISLE',
            'booking.selectedSeat' => 'Selected Seat',
            'booking.seatVIP' => 'Seat No. %s (VIP)',
            'booking.seatFree' => 'Seat %s Available',
            'booking.seatOccupied' => 'Seat Occupied',
            'booking.ticketPrice' => 'Ticket Price',
            'booking.back' => 'Back',
            'booking.continueToPay' => 'Proceed to Payment ➔',
            'booking.passengerInfo' => 'Passenger Information',
            'booking.passengerName' => 'Full Passenger Name *',
            'booking.passengerId' => 'National ID or Passport No.',
            'booking.phone' => 'Mobile Money Number (9 digits)',
            'booking.email' => 'Email Address (Optional)',
            'booking.operator' => 'Mobile Money Operator',
            'booking.phoneHelp' => '+237 Cameroon country code is handled automatically.',
            'booking.payBtn' => 'Pay 5,000 XAF with CamPay',
            'booking.loadingDepartures' => 'Searching live scheduled departures...',
            'booking.noDepartures' => 'No departures scheduled on this route for %s.',
            'booking.seeTomorrow' => 'View tomorrow\'s departures',
            'booking.chooseSeat' => 'Select Seat ➔',
            'booking.connectingCampay' => 'Connecting to CamPay...',
            'booking.pendingTitle' => 'Debit Request Transmitted to CamPay!',
            'booking.pendingDesc' => 'A payment prompt was sent to your phone. Please authorize with your secret PIN.',
            'booking.actionRequired' => 'Action Required on Phone:',
            'booking.ussdHelp' => 'If the prompt does not appear, dial the USSD code directly below:',
            'booking.ticketBlockedHelp' => '⏳ E-Ticket cannot be downloaded until debit is confirmed by operator.',
            'booking.checkStatus' => 'Check Payment Status',
            'booking.autoDetecting' => 'Detecting mobile payment automatically in real-time...',
            'booking.verifyingPayment' => 'Verifying CamPay payment status...',
            'booking.demoConfirm' => 'Automatic payment detection in progress...',
            'booking.successTitle' => 'Payment Confirmed & Boarding Pass Validated!',
            'booking.successDesc' => 'Your booking is permanently recorded in our database. Have a safe journey with Global Voyages!',
            'booking.paidTicket' => '✓ Validated Boarding Pass',
            'booking.downloadTicket' => 'Download Boarding Pass (HTML / PDF)',
            'booking.close' => 'Done & View My Bookings',

            // Customer Dashboard
            'customer.vipWelcome' => 'VIP Passenger Portal',
            'customer.newTicket' => 'New Ticket',
            'customer.reportIssue' => 'Report Issue',
            'customer.tabTickets' => 'My Bus Tickets',
            'customer.tabParcels' => 'My Parcels & Luggage',
            'customer.tabNotifications' => 'Notifications',
            'customer.tabIssues' => 'My Support Tickets',
            'customer.paid' => 'Validated & Paid Ticket',
            'customer.pending' => 'Pending Payment',
            'customer.cancelled' => 'Booking Cancelled',
            'customer.passenger' => 'Passenger',
            'customer.cancel' => 'Cancel',
            'customer.pay' => 'Pay OM/MoMo',
            'customer.ticket' => 'Ticket 🖨️',
            'customer.track' => 'Track ➔',
            'customer.waybill' => 'Waybill 🖨️',
            'customer.noTickets' => 'No tickets booked yet',
            'customer.buyNow' => 'Book a ticket now',
            'customer.noParcels' => 'No parcels recorded yet',
            'customer.noIssues' => 'No support tickets reported yet.',
            'customer.newReport' => 'New Report',
            'customer.close' => 'Close',

            // Footer
            'footer.tagline' => 'Premier intercity transport network in Cameroon. Real-time GPS-tracked VIP coaches and secure parcel logistics.',
            'footer.mainRoutes' => 'Main Corridors',
            'footer.routeDlaYao' => 'Douala (Akwa) ➔ Yaounde (Mvan) Express N3',
            'footer.routeYaoDla' => 'Yaounde (Mvan) ➔ Douala (Akwa) Express N3',
            'footer.departuresFreq' => 'Daily departures every 2.5 hours',
            'footer.escaleBoum' => 'Boumnyebel gourmet travel break',
            'footer.securePayment' => 'Secure Payment',
            'footer.campayDesc' => 'Instant mobile payments via MTN Mobile Money (*126#) and Orange Money (#150*50#).',
            'footer.support' => '24/7 Customer Care',
            'footer.customerService' => 'Luggage & Customer Service:',
            'footer.copyright' => 'All rights reserved.',

            // Roles
            'role.admin' => 'Administrator',
            'role.driver' => 'Driver',
            'role.booking_agent' => 'Booking Agent',
            'role.parcel_agent' => 'Parcel Agent',
            'role.customer' => 'Customer',

            // Login
            'login.title' => 'Secure Login',
            'login.subtitle' => 'Access your Global Voyages workspace',
            'login.demoQuick' => 'Instant 1-Click Demo Access',
            'login.orCredentials' => 'or with credentials',
            'login.username' => 'Username or Email',
            'login.password' => 'Password',
            'login.submit' => 'Sign In',
            'login.invalid' => 'Invalid credentials.',

            // Waybill
            'waybill.title' => 'Parcel Shipment Waybill',
            'waybill.badge' => 'CONSIGNMENT WAYBILL',
            'waybill.origin' => 'Origin Station',
            'waybill.dest' => 'Destination Station',
            'waybill.sender' => 'Sender',
            'waybill.recipient' => 'Recipient',
            'waybill.weight' => 'Weight & Dimensions',
            'waybill.fees' => 'Charges:',
            'waybill.declaredValue' => 'Declared Value',
            'waybill.insurance' => 'VIP Cargo insurance included',
            'waybill.content' => 'Cargo Description',
            'waybill.standardParcel' => 'Standard cargo parcel',
            'waybill.tracker' => '4G IoT GPS Tracker',
            'waybill.unassigned' => 'Unassigned',
            'waybill.trackingNum' => 'Parcel Tracking Number',
            'waybill.status' => 'Status:',
            'waybill.senderSig' => 'Sender Signature:',
            'waybill.agentSig' => 'Agent Stamp & Signature:',
            'waybill.notice' => 'Present this waybill or tracking number to collect your parcel.',
            'waybill.print' => '🖨️ Print Consignment Waybill',

            // Agent
            'agent.bookingDesk' => 'VIP Ticketing & Baggage Desk',
            'agent.parcelDesk' => 'Cargo, Parcel & Freight Desk',
            'agent.operationalMgmt' => 'Douala (Akwa) ↔ Yaounde (Mvan) • Operations Management',
            'agent.newParcel' => 'New Parcel',
            'agent.tabParcels' => '📦 Parcel Agent Workspace',
            'agent.tabBookings' => '🎫 Booking Agent Workspace',
            'agent.parcelsTitle' => 'Parcel & Cargo Shipment Management',
            'agent.parcelsSub' => 'Registration, Weighing, Checkpoints & Audit Log',
            'agent.searchPlaceholder' => 'Search by tracking no, sender...',
            'agent.colNumber' => 'Reference',
            'agent.colSender' => 'Sender',
            'agent.colRecipient' => 'Recipient',
            'agent.colRoute' => 'Route',
            'agent.colWeightFees' => 'Weight / Fee',
            'agent.colTracker' => 'IoT Tracker',
            'agent.colStatus' => 'Status',
            'agent.colActions' => 'Actions',
            'agent.none' => 'None',
            'agent.btnStatus' => 'Status ⚙️',
            'agent.btnHistory' => 'Timeline 📜',
            'agent.btnWaybill' => 'Waybill 🖨️',
            'agent.bookingsTitle' => 'Bookings & Baggage IoT Tagging',
            'agent.bookingsSub' => 'Supervise travelers, validate desk payments and attach physical IoT trackers to luggage',
            'agent.colRef' => 'Reference',
            'agent.colPassenger' => 'Passenger (Profile)',
            'agent.colTrip' => 'Trip',
            'agent.colSeat' => 'VIP Seat',
            'agent.colDateTime' => 'Date & Time',
            'agent.colLuggageTracker' => 'Baggage IoT Tracker',
            'agent.colPayment' => 'Payment',
            'agent.colDeskActions' => 'Desk Actions',
            'agent.unassigned' => 'Unassigned',
            'agent.btnLinkTracker' => 'Attach IoT Tracker 🏷️',
            'agent.btnDeskCollect' => 'Collect at Desk',
            'agent.btnTicket' => 'Boarding Pass 🖨️',
            'agent.modalAssignTitle' => 'Attach IoT Tracker to Luggage',
            'agent.modalAssignSub' => 'Select Physical IoT Tracker Beacon *',
            'agent.btnCancel' => 'Cancel',
            'agent.btnAttach' => 'Attach to Baggage',
            'agent.modalHistoryTitle' => 'Parcel Shipment Checkpoint History',
            'agent.noHistory' => 'No checkpoints recorded yet.',
            'agent.btnClose' => 'Close',
            'agent.modalStatusTitle' => 'Update Parcel Checkpoint Status',
            'agent.colisConcerned' => 'Target Parcel',
            'agent.newStatusLabel' => 'New Transit Status',
            'agent.currentStationLabel' => 'Current Station / Checkpoint',
            'agent.notesLabel' => 'Checkpoint Notes & Observations',
            'agent.notesPlaceholder' => 'E.g. Package inspected, seal intact, loaded in VIP hold...',
            'agent.btnSaveStatus' => 'Save Status',
            'agent.modalRegisterTitle' => 'Register Parcel at Counter',
            'agent.senderName' => 'Sender Name *',
            'agent.senderPhone' => 'Sender Phone *',
            'agent.recipientName' => 'Recipient Name *',
            'agent.recipientPhone' => 'Recipient Phone *',
            'agent.recipientAddress' => 'Delivery Address / Neighborhood *',
            'agent.originStation' => 'Origin Station',
            'agent.destStation' => 'Destination Station',
            'agent.weightKg' => 'Weight (kg) *',
            'agent.shippingFee' => 'Shipping Fee (500 XAF/kg)',
            'agent.declaredValue' => 'Declared Value (XAF)',
            'agent.trackerSelect' => 'Attached IoT Tracker',
            'agent.trackerNone' => 'None (Standard Cargo)',
            'agent.description' => 'Contents Description',
            'agent.descriptionPlaceholder' => 'E.g. Legal documents, spare parts, personal effects...',
            'agent.btnRegisterSubmit' => 'Register & Issue Waybill',

            // Admin
            'admin.bannerTitle' => 'Central Supervision & Administration',
            'admin.bannerSubtitle' => 'User Accounts, IoT Trackers, Douala ↔ Yaounde Schedules & Ticketing',
            'admin.newTrip' => 'New Scheduled Trip',
            'admin.kpiRevenue' => 'Total Revenue',
            'admin.kpiBookings' => 'Tickets Booked',
            'admin.kpiParcels' => 'Parcels & Freight',
            'admin.kpiTrips' => 'Highway N3 Trips',
            'admin.kpiUsers' => 'User Accounts',
            'admin.kpiTrackers' => '4G IoT Trackers',
            'admin.tabUsers' => 'User Accounts',
            'admin.tabIoT' => 'IoT Devices',
            'admin.tabBookings' => 'Ticket Bookings',
            'admin.tabTrips' => 'Scheduled Trips',
            'admin.tabParcels' => 'Freight & Parcels',
            'admin.usersTitle' => 'System User Management (Admin, Agents, Drivers, Customers)',
            'admin.usersSub' => 'Update, ban/unban or delete user accounts',
            'admin.colId' => 'ID',
            'admin.colFullName' => 'Full Name',
            'admin.colUsername' => 'Username / Email',
            'admin.colPhone' => 'Phone',
            'admin.colRole' => 'Role',
            'admin.colStatus' => 'Status',
            'admin.colActions' => 'Actions',
            'admin.statusBanned' => 'BANNED / SUSPENDED',
            'admin.statusActive' => 'ACTIVE',
            'admin.btnEdit' => 'Edit ✏️',
            'admin.btnBan' => 'Ban',
            'admin.btnUnban' => 'Unban',
            'admin.btnDelete' => 'Delete 🗑️',
            'admin.iotTitle' => '4G IoT Tracker Fleet Management (Highway N3)',
            'admin.iotSub' => 'Supervise battery levels, GPS coordinates and assign to convoys',
            'admin.btnAddTracker' => '+ Add IoT Tracker',
            'admin.colTrackerCode' => 'Tracker Code',
            'admin.colModel' => 'Device Model',
            'admin.colBattery' => 'Battery',
            'admin.colGpsPos' => 'Last GPS Position',
            'admin.colSpeed' => 'Speed',
            'admin.statusAvailable' => 'AVAILABLE',
            'admin.statusAssigned' => 'ASSIGNED',
            'admin.statusMaintenance' => 'MAINTENANCE',
            'admin.tripsTitle' => 'Highway N3 Intercity Departures Management',
            'admin.tripsSub' => 'Daily scheduling of direct non-stop Douala ↔ Yaounde departures',
            'admin.colTripNum' => 'Trip No.',
            'admin.colLine' => 'Route',
            'admin.colBus' => 'VIP Coach',
            'admin.colDriver' => 'Driver',
            'admin.colDeparture' => 'Scheduled Departure',
            'admin.colArrival' => 'Estimated Arrival',
            'admin.colFare' => 'Fare',
            'admin.unassignedDriver' => 'Unassigned',

            // Driver
            'driver.deckTitle' => 'Driver Cockpit • Highway N3 Douala ↔ Yaounde',
            'driver.deckSub' => '4G GPS Telemetry • Scania VIP First Class',
            'driver.gpsOnline' => 'GPS Online (Battery: %s%%)',
            'driver.navTitle' => 'Live Highway N3 Route • Douala ↔ Yaounde (Carto HD)',
            'driver.assignedTrips' => 'Assigned Douala ↔ Yaounde Trips',
            'driver.coach' => 'VIP Coach',
            'driver.scheduledDep' => 'Scheduled Departure',
            'driver.scheduledArr' => 'Estimated Arrival',
            'driver.btnDepart' => 'Confirm Departure 🚀',
            'driver.btnArrive' => 'Confirm Arrival 🏁',
            'driver.updateGpsStop' => 'Update GPS Checkpoint / N3 Stop',
            'driver.currentSpeed' => 'Current Speed (km/h)',
            'driver.btnUpdatePosition' => 'Update GPS Position',
            'driver.reportIncident' => 'Trip Report / Route Incident',
            'driver.btnTransmitReport' => 'Transmit Report',
        ]
    ];

    public static function get(string $key, ?string $fallback = null): string {
        $lang = self::current();
        return self::$translations[$lang][$key] ?? ($fallback ?? $key);
    }

    public static function current(): string {
        if (isset($_GET['lang']) && in_array($_GET['lang'], ['fr', 'en'])) {
            if (session_status() === PHP_SESSION_ACTIVE) {
                $_SESSION['lang'] = $_GET['lang'];
            }
            return $_GET['lang'];
        }
        $lang = $_SESSION['lang'] ?? 'fr';
        if (!in_array($lang, ['fr', 'en'])) {
            $lang = 'fr';
        }
        return $lang;
    }

    public static function isEn(): bool {
        return self::current() === 'en';
    }

    public static function getAllForCurrent(): array {
        $lang = self::current();
        return self::$translations[$lang] ?? self::$translations['fr'];
    }
}

function t(string $key, ?string $fallback = null): string {
    return Language::get($key, $fallback);
}
